// Quote model interface - defines structure for saved quotes
// Used in budget.ts service and budgets-list.ts component
export interface Quote {
  // Unique identifier generated by crypto.randomUUID()
  id: string;
  // Client contact information
  clientName: string;
  phone: string;
  email: string;
  // Selected services for this quote
  services: {
    seo: boolean;
    ads: boolean;
    web: boolean;
  };
  // Website configuration - only applies when web service selected
  webConfig: {
    pages: number;
    languages: number;
  };
  // Total calculated price in euros
  totalPrice: number;
  // Quote creation timestamp
  createdAt: Date;
}
